### ISSUE TITLE
Automating the release process

### ISSUE THREAD

**Issue by izyuumi** [floris-xlx/supabase_rs#13]
This is only a suggestion (and I don't know how you handle it currently), but it may be beneficial to automate the releasing and versioning process with GitHub Actions. I developed [this crate](https://github.com/izyuumi/html2md-rs) and I've been using GitHub Actions to automate the releasing process using. The GitHub Actions configuration file is [here](https://github.com/izyuumi/html2md-rs/blob/main/.github/workflows/release.yml).

**Comment by floris-xlx** [comment]
solid idea i was looking for something like this, i might add a clause to also run tests

**Comment by floris-xlx** [comment]
looks very cool, im not sure how it's generating that bug fix/ feat overview but nicely done i integrated it

**Comment by izyuumi** [comment]
The changelog is automatically inferred from the commit messages, which are in the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format.
