### ISSUE TITLE
Release workflow is run automatically and always fails

### ISSUE THREAD

**Issue by strykejern** [floris-xlx/supabase_rs#26]
The [`release.yml`](https://github.com/floris-xlx/supabase_rs/blob/ead19d29595d4eabdb3f6f201bc453765bfdcc19/.github/workflows/release.yml) workflow seems to be set up to automatically  run on each push to `main`. Do we really want this? What about changing it to a manually triggered workflow to better control when we publish, and to better communicate semantic versioning?

It's also set to run on a self-hosted runner, which seems to fail. Is the runner(s) down? What is the reason for using self-hosted instead of standard runners?

**Comment by floris-xlx** [comment]
yeah i seem to recall that runners tokens only last for 90 days or something, no clue why that is. i just restarted the one for this repo and it seems to be working fine

![image](https://github.com/user-attachments/assets/eef512ce-9c34-44fb-9086-a1528e81e1ec)

github has incredibly slow compute and we have excess anyways so it doesnt matter how many times or how long it runs

**Comment by floris-xlx** [comment]
@strykejern would you happen to have discord or something? easier to coordinate things than over a git PR:)

my discord @floris_xlx
