### ISSUE TITLE
Update a row that has primary key column not named `id`

### ISSUE THREAD

**Issue by izyuumi** [floris-xlx/supabase_rs#3]
I have a column not named `id` I want to reference when updating a row. With the current implementation of the update operation, `id` is the only possible column I could reference when updating. I believe https://docs.rs/supabase_rs/0.3.1/src/supabase_rs/update.rs.html#65 is the line where `id` is hard coded. Would it be cool if I make a PR with another function that allows users to select the column name they want to reference when updating?

**Comment by izyuumi** [comment]
Let me know what you think of this implementation: https://github.com/izyuumi/supabase_rs/commit/b2de62944a8f682b6a9d2664bcf2926617420919

**Comment by floris-xlx** [comment]
I will make this change-able in supabase_rs 0.3.2 tonight! (within 12-14hrs) i'll make sure it's out

thank you for the issue!!

**Comment by floris-xlx** [comment]
This is how you would right now in 0.3.1 update a value based on the query of a given column value, column name, table name,
without it's original ID

```rust
pub async fn update_column_value(
    foobar: &str
) -> Result<(), String> {
    let client: SupabaseClient = initialize_supabase_client().await;
    let table_name: &str = "foo";
    let column_name: &str = "bar";

    // get the row id from the organization name
    let row_id: Result<String, String> = SupabaseClient::get_id(
        client.clone(), // irrigate w the client
        foobar.to_string().clone(),  // pass our column value
        table_name.to_string().clone(),  // our table name
        column_name.to_string() // our target column name ( this is what the column value needs to .eq to in order to resolve)
    ).await;

    let row_id: String = row_id.unwrap();

    let update_result: Result<(), String> = client
      .update( 
         table_name, 
          &row_id,
          json!({
              "any_column_in_the_row": "updated_value!",  // the new value 
          }),
      ).await;

    Ok(())
}
```
but as i said earlier i will make it a bit easier as this is clearly not the best way to do so

**Comment by floris-xlx** [comment]
merged your PR, makes 100x more sense than whatever the fuck i was doing here months ago:) thanks!

added you in the bottom of the docs.rs & readme.md under the # contributors tag,

happy coding

**Comment by izyuumi** [comment]
Thanks!
