### ISSUE TITLE
`insert` assumes `id` to exist and to be type of `i64`

### ISSUE THREAD

**Issue by izyuumi** [floris-xlx/supabase_rs#6]
As shown on [this line](https://docs.rs/supabase_rs/latest/src/supabase_rs/insert.rs.html#102), the `insert` function assumes `id` to exist and to be type of `i64`. However, there could be use cases where the primary key might not be `id` and even if it does, could be non-numerical types like UUID. Also, from the security aspect, it may not be ideal to allow the client side to determine the `id` as it could override already existing rows if RLS and such are not properly configured.

Suggestion:
- `insert_without_defined_key` function that allows the Supabase backend to determine the value of the primary key, whether it be numerical `id`, UUID `uuid`, or anything else. This would allow various types of databases to use this crate with one less thing to think about. Also, if users want to use a custom primary key, they would be able to do so by just passing it in as a field in the body.

**Comment by izyuumi** [comment]
Let me know if you find any issues, I will try to fix them.

**Comment by floris-xlx** [comment]
what did you reckon then as replacement, default force it into type static str ?

**Comment by izyuumi** [comment]
As you probably have seen already in my PR, it might be enough to just let the user pass in the primary key column name and value, if they want to set it on client side. If you think there should be a function that requires users to pass in a primary key column name and a value for that column, I would say that it might be useful to have another function that takes in a key and value for the primary key.

**Comment by floris-xlx** [comment]
im overthinking it, it's a seperate method anyways so it won't break pre-existing code. i'll add a test case and merge your PR in a sec
