### ISSUE TITLE
Could the bulk insert feature just be a wrapper for the insert function that takes in a `Vec` of values?

### ISSUE THREAD

**Issue by izyuumi** [floris-xlx/supabase_rs#8]
As shown in the screenshot I took from the [Auto-generated documentation](https://supabase.com/docs/guides/api/rest/auto-generated-docs) page, it looks like the bulk inserting is using the same API endpoint as inserting, just that bulk inserting passes an array of values instead of a single one. Does this mean that the bulk insert feature could be implemented by creating a similar function to `insert` that takes a `Vec` of values as an argument? If so, I could implement that :)
![CleanShot 20240708 063736](https://github.com/floris-xlx/supabase_rs/assets/36561306/b593773f-9992-4a14-be15-11826d234bba)

**Comment by floris-xlx** [comment]
im pretty sure supabase.py does the same which i modeled supabase_rs after.


when i merge your other PR today i will add this including some other things.

this is the most complete and most downloaded supabase sdk for rust, so if we cover the entire api we can probably get our names listed under the rust SDK on their docs page  :P
